### ISSUE TITLE
Search Results Broken

### ISSUE THREAD

**Issue by PerpetualStudio** [zeon-studio/astroplate#1]
The URLs generated by the search results component are all undefended. Clicking on the title or read more button results in a 404 error.

It looks like you can fix this by changing the links inside Search.tsx

From <a href={`/${blog_folder}/${item.data.slug}`}>
To <a href={`/${blog_folder}/${item.slug}`}>

I'm not sure if this is a fix or more of a hack.

**Comment by tfsomrat** [comment]
Hello @PerpetualStudio 

thanks for noticing the issue. I fixed it. please re-download and enjoy.
