### ISSUE TITLE
The testimonial slider on the home page is not functioning as expected.

### ISSUE THREAD

**Issue by tfsumon** [zeon-studio/astroplate#17]
**Problem**: The testimonial slider on the home page is not functioning as expected.

**Scenario**: When a user visits the home page and then navigates to another page, upon returning to the home page, the testimonial slider is not working.

**Steps to Reproduce**:

- Visit the home page.
- Interact with the testimonial slider to ensure it's working initially.
- Navigate to another page.
- Return to the home page.
- Expected Behavior: The testimonial slider on the home page should continue to work correctly, even after navigating to other pages and returning.

**Actual Behavior**: The testimonial slider on the home page becomes non-functional upon returning from other pages.

**Environment**:
- OS: macOS
- Browser: Chrome
- Version: 118.0.5993.70

**Reproducibility**: Always

**Possible Solution**: The issue may be related to the use of view transitions. It seems to occur after navigating between pages using view transitions. Please check the implementation of view transitions to identify and resolve any conflicts or issues that might be causing the problem.

**Comment by tfsomrat** [comment]
thanks, issue has been fixed.
