### ISSUE TITLE
SSG not working

### ISSUE THREAD

**Issue by jcarloscandela** [zeon-studio/astroplate#19]
I configured the site in Netlify and Vercel and the visualization is not working correctly, cannot load the styles.
It only works when I am running the project using **astro dev**
Any idea?

**Comment by tfsomrat** [comment]
Hey @jcarloscandela, try to change the `base_url` https://github.com/zeon-studio/astroplate/blob/7aa8bf8b49afe129f2bba30c0df0fad8902d3745/src/config/config.json#L4

**Comment by jcarloscandela** [comment]
Ty, I solved it
