### ISSUE TITLE
DeprecationWarning: Invalid 'main' field ... 

### ISSUE THREAD

**Issue by jjaimealeman** [zeon-studio/astroplate#2]
Upon fresh `git clone` I get the following error.

![image](https://github.com/zeon-studio/astroplate/assets/1428292/b559e334-e1db-4d9c-9fb1-9d08526a80a1)

Project still runs fine.

Just wanted to bring that to your attention 👍🏽

**Comment by jjaimealeman** [comment]
Upon further testing amigo, I discovered errors on `/posts` and `/authors`.

Also on mobile, the drop menu is not centered.

Attached is a short 

https://github.com/zeon-studio/astroplate/assets/1428292/d545edaa-c4ba-49f3-b986-06796c11be08

In case the video came out blurry or illegible, here are a few screenshots.

![image](https://github.com/zeon-studio/astroplate/assets/1428292/30f46668-26f5-494b-833a-6fc5d66da3b9)

![image](https://github.com/zeon-studio/astroplate/assets/1428292/ec31429c-bf05-40c0-875f-d497a38c221f)

![image](https://github.com/zeon-studio/astroplate/assets/1428292/bfa64f9b-1e04-4905-a6b5-064a6bdbf4df)

**Comment by jjaimealeman** [comment]
I filed to mention my versions:

```
node --version = v18.12.0
npm --version = 8.19.2
yarn --version = 1.22.19
```
👍🏽

**Comment by tfsomrat** [comment]
hey @jjaimealeman 

Thanks for pointing out this issue, I have added a fix for the issue. please check it now.

**Comment by jjaimealeman** [comment]
Excellent amigo.

Thanks!

Have a good weekend.
