### ISSUE TITLE
How I can remove "2XL" badge?

### ISSUE THREAD

**Issue by corradiniste** [zeon-studio/astroplate#24]
How I can remove "2XL" badge?

![Screenshot 2023-12-12 alle 16 30 14](https://github.com/zeon-studio/astroplate/assets/12842138/7a71cfaf-ac63-4502-bd09-e62e909bf463)

**Comment by tfsomrat** [comment]
Hey @corradiniste, you don't need to worry about the badge. it's only for development purposes, it won't show on the production build. happy coding.
