### ISSUE TITLE
Disqus Setting

### ISSUE THREAD

**Issue by rizfahma** [zeon-studio/astroplate#25]
Hello

I am using this theme on my machine, I am a newbie, actually... How to setup the disqus comment section? I mean is there any way to setup so I can use my disqus account? Thank you

**Comment by tfsomrat** [comment]
hey @rizfahma, here is a blog post about how to set up Disqus on Hugo, but don't freak out. you just need to find out how to create a. shortname for Disqus. and use this shortname on the theme config.

**Comment by rizfahma** [comment]
> hey @rizfahma, here is a blog post about how to set up Disqus on Hugo, but don't freak out. you just need to find out how to create a. shortname for Disqus. and use this shortname on the theme config.

Thank you, Somrat
