### ISSUE TITLE
The safelist pattern `/swiper-/` doesn't match any Tailwind CSS classes. 

### ISSUE THREAD

**Issue by Drsheppard01** [zeon-studio/astroplate#26]
Can u help me resolve this issue?
It was when i deploy this boilerplate in github

hub.com/Drsheppard01/appimages

**Comment by tfsomrat** [comment]
Hey @Drsheppard01, It's not an issue, it's a warning. and if you remove the safelist, your swiper slider will break. so leave it as it is. thanks

**Comment by Drsheppard01** [comment]
But swiper provide swiper pagination class and i think i has break images, 'cause tailwind just skip swiper

Deployed site: drsheppard01.github.io/appimages

**Comment by tfsomrat** [comment]
It has nothing to do with swiper. try to add your deployed URL into `config/config.json` files `baseurl` field. hope it will work

**Comment by Drsheppard01** [comment]
Yep, i find issue
It will be happening 'cause i use link drsheppard01.github.io/appimages, which didn't wrote in config file
