### ISSUE TITLE
List latest X items in home

### ISSUE THREAD

**Issue by javimata** [zeon-studio/astroplate#31]
Hello, excellent work, congratulations

I would like to show the latest X articles from my blog on my home, how can I do it? Is there a function already created or should I do it?

Thank you and again congratulations for such a good job.

**Comment by tffarhad** [comment]
Hi @javimata,
Thank you for your kind words. The function you are looking for has not been created yet. You will need to create it. If you need help with implementing this or any other customization, you can contact us at https://zeon.studio/estimate-project 

Thank you.
