### ISSUE TITLE
Keyboard navigation for Tabs and accordion elements?

### ISSUE THREAD

**Issue by rnwolf** [zeon-studio/astroplate#4]
The new tabs element is great but I was wondering about accessibility for the tabs.

I see that this site below allows me to keyboard tab to the "tabs" and then use the arrow keys to move from tab to tab.

http://web-accessibility.carnegiemuseums.org/code/tabs/

**Comment by rnwolf** [comment]
I suppose the same accessibility question applies to the accordion element. I don't seem to be able to use the keyboard to navigate to them and toggle contents.

Like the example here https://www.hassellinclusion.com/blog/accessible-accordions-part-2-using-details-summary/

**Comment by rnwolf** [comment]
I added <detail> and <summary> tags for the accordion and it seems to work in Edge. 
![image](https://github.com/zeon-studio/astroplate/assets/117415/bbab7e06-f926-4526-aeb5-22bc0c97634f)

**Comment by tfsomrat** [comment]
Hello @rnwolf 

Thanks for your concern. we just launch the Tab yesterday. it was very difficult to create a Tab component for Astro. we will start work on accessibility very soon.

**Comment by tfsomrat** [comment]
Hey @rnwolf, we have added accessibility for the tab and accordion component. give it a try.

**Comment by rnwolf** [comment]
Keyboard navigation is working great for both tab and accordion components. Brilliant.
