### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by Thebuilderekes** [zeon-studio/astroplate#6]
Please I need help. I'd appreciate it if anyone can point me to the exact line(s) of code or process in the codebase that made the 404 page reachable whenever a visitor tries to search for a page that does not exist. I'm new to learning and building with astro and i'd really love to know how this was implemented. Thanks.

**Comment by tfsomrat** [comment]
Hey @Thebuilderekes  checkout this link: https://docs.astro.build/en/core-concepts/astro-pages/#custom-404-error-page

**Comment by Thebuilderekes** [comment]
This worked just fine. Thank you.

**Comment by Thebuilderekes** [comment]
Thank you.
