### ISSUE TITLE
Dockerfile does not work

### ISSUE THREAD

**Issue by Alfagun74** [zeon-studio/astroplate#8]
I tried to follow this Guide in the README:

![image](https://github.com/zeon-studio/astroplate/assets/22225051/38b46807-218b-420c-add1-16e7910ff8cf)

but i got. Reproducable on the bare repository without changing anything.

```
docker run -p 3000:3000 astroplate                                                                                        ✔   28s  ⬢ 20.2.0  11:30:09 
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '/app/server.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.17.0
```

**Comment by tfsomrat** [comment]
Hey @Alfagun74 

Sorry for the inconvenience, I also got the error on my site. I will fix it when I got some time. In the meantime you can follow their original docker file from here https://docs.astro.build/en/recipes/docker/#creating-a-dockerfile

**Comment by jjaimealeman** [comment]
As a semi-newb to using Astro, what's the purpose of using Docker here?

**Comment by Alfagun74** [comment]
@jjaimealeman to deploy the site on a server for example.
